import {
  GraphQLString,
  GraphQLObjectType,
  GraphQLInt
} from 'graphql'

export default new GraphQLObjectType({
  name: 'payment',
  description: 'Installments',
  fields: {
    id: {
      type: GraphQLString,
      description: 'An unique id generated by mongodb'
    },
    date: {
      type: GraphQLString
    },
    amount: {
      type: GraphQLInt
    }
  }
})
